### ISSUE TITLE
EEPROM не считывается.

### ISSUE THREAD

**Issue by Sevas55** [StartMilandr/1.3-EEPROM_WR_RD#1]
Здравствуйте.
Возникла проблема с работой с EEPROM. Предварительная настройка проекта кейла сделана, согласно ваших рекомендаций на сайте.
Контроллер K1986BE92QI

Данный код работает и записанные данные правильно считываются - число 55.

```
 #define F_CPU 64000000UL
 
 #include <stdio.h
 #include <stdbool.h
 
 #include <MDR32F9Qx_port.h
 #include <MDR32F9Qx_rst_clk.h
 #include <MDR32F9Qx_uart.h
 #include "MDR32F9Qx_timer.h"
 #include "MDR32F9Qx_wwdg.h"
 #include "MDR32F9Qx_eeprom.h"
 
 #include "CPU_INIT.h"
 #include "MDR32Fx.h"                    // Device header
 #include "UART_INIT.h"
 #include "PORTS_INIT.h"
 #include "DELAY.h"   
 #include "I2C_INIT.h"
 #include "MPU6050.h"
 #include "HMC5883L.h"
 
 #define EEPROM_PAGE_SIZE             (256*32) //изменено, согласно даташиту на K1986BE92QI
 #define MAIN_EEPAGE                  5
 
 int main(void)
 {
 	CPU_INIT();
 	UART_INIT();
 	PortC_Pin2_init();//светодиод PC2
 	SysTick_Config(F_CPU/1000);//delay 1ms
 	uint32_t Address = 0;
        uint32_t BankSelector = 0;
        uint32_t Data = 0;
 	
 	RST_CLK_PCLKcmd(RST_CLK_PCLK_EEPROM, ENABLE);
 	EEPROM_SetLatency(EEPROM_Latency_7);
 	Address = 0x08000000 + MAIN_EEPAGE * EEPROM_PAGE_SIZE;
        BankSelector = EEPROM_Main_Bank_Select;
 	Data = 55;
 	EEPROM_ProgramWord (Address , BankSelector, Data);
 
  
 	uint32_t b1 = EEPROM_ReadWord(Address, EEPROM_Main_Bank_Select);
 	RST_CLK_PCLKcmd(RST_CLK_PCLK_EEPROM, DISABLE);
 
 	while(1)
 	{
 		delay_ms(500);
 		MDR_PORTC-RXTX ^= 1<<2;//светодиод PC2	
 		printf("%d\n", b1); 		
 	}
 }
```

Если перепрошить контроллер с тем же кодом, но без команды записи в EEPROM, то по идее должна считаться информация по тому же адресу что из предыдущего кода.
Однако данные считываются как -1 (минус 1), а должно быть 55.
Похоже как будто данные eeprom вообще не сохраняются.

Подскажите в чем может быть проблема?
Спасибо

**Comment by StartMilandr** [comment]
Здравствуйте.

Если перепрошивка происходит через штатный FLM из пака, то он стирает всю память EEPROM целиком. С опцией стирания по секторам в Keil этот FLM не работает. Полагаю поэтому после перепрошивки программы ячейка сдержит стертое значение (0хFFFFFFFF), а не 55. 

Можно попробовать использовать информационную память. Но надо учесть, что при стирании информационной памяти, автоматически стирается и основная.

Попытка сделать FLM со стиранием по секторам в этой статье - https://startmilandr.ru/doku.php/prog:start:newflm
